"""
This module contains lists of Indian first names and last names, prefixes and nouns for generating names of educational institutes, data types, sports and hobbies.
"""

indian_student_first_names = [
    "Aarav", "Aditi", "Akshay", "Alisha", "Amit", "Anika", "Ankit", "Anushka", "Arjun", "Bhavna",
    "Chirag", "Devika", "Divya", "Esha", "Gautam", "Geeta", "Harsh", "Ishita", "Jatin", "Kajal",
    "Karan", "Kavya", "Mahesh", "Manisha", "Mihir", "Minakshi", "Mohit", "Mridula", "Naveen", "Neha",
    "Nikhil", "Nisha", "Pankaj", "Pooja", "Pranav", "Priya", "Rahul", "Rhea", "Rishi", "Ritu", "Rohan",
    "Saanvi", "Sagar", "Sahana", "Sameer", "Sanaya", "Shivam", "Shreya", "Siddharth", "Simran", "Suman",
    "Suraj", "Swati", "Tanish", "Tanvi", "Tarun", "Trisha", "Udit", "Ujjwala", "Varun", "Veda", "Vicky",
    "Vidya", "Vikas", "Vishakha", "Yash", "Yashika", "Yuvraj", "Zara", "Aarushi", "Abhinav", "Aishwarya",
    "Anand", "Ananya", "Ankita", "Ayush", "Charul", "Danish", "Eesha", "Faizan", "Gargi", "Gaurav", "Ishaan",
    "Jyoti", "Kanishka", "Khushi", "Madhav", "Meenakshi", "Nandini", "Omkar", "Parth", "Rani", "Ritika",
    "Roshan", "Sanya", "Shashank", "Shikha", "Sooraj", "Tanya", "Vinit"
]
indian_student_last_names = [
    "Sharma", "Verma", "Patel", "Singh", "Kumar", "Gupta", "Mishra", "Yadav", "Rao", "Agarwal",
    "Das", "Choudhary", "Mehta", "Sinha", "Jain", "Pandey", "Roy", "Chauhan", "Reddy", "Thakur",
    "Banerjee", "Nair", "Shah", "Srivastava", "Bose", "Jha", "Saxena", "Rajput", "Malik", "Seth",
    "Mukherjee", "Rana", "Bhat", "Dubey", "Nag", "Dutta", "Barman", "Goswami", "Verma", "Narayan",
    "Biswas", "Yadav", "Chakraborty", "Khan", "Sharma", "Sawant", "Tiwari", "Srivastava", "Kamble",
    "Shukla", "Meena", "Kaur", "Gavde", "Kulkarni", "Joshi", "Rathore", "Mohanty", "Kadam",
    "Sawhney", "Kulkarni", "Shroff", "Sharma", "Saraf", "Kapoor", "Rathore", "Dixit", "Bhat",
    "Khanna", "Trivedi", "Seth", "Mistry", "Chauhan", "Chatterjee", "Mehta", "Deshmukh", "Pawar",
    "Nair", "Verma", "Shah", "Vyas", "Jain", "Bhardwaj", "Rathore", "Kumari", "Yadav", "Biswas",
    "Rai", "Reddy", "Yadav", "Sen", "Acharya", "Joshi", "Rajput", "Amin", "Raj", "Choudhary", "Nayak"
]

prefixes = [
    "National", "International", "Global", "Elite", "Advanced", "Institute of", "School of", "Academy of",
    "Innovation", "Excellence", "Institute for", "Center for", "Institute of Technology", "Science Institute",
    "Research Institute", "Institute of Business", "Academy of Arts", "Institute of Engineering", "Center for Education",
    "Center for Medicine", "Institute of Management", "Institute of Science", "Institute of Art", "Academy of Medicine",
    "Institute of Design", "Institute of Information Technology", "Institute of Communication", "Institute of Medicine",
    "Institute of Education", "Institute of Management", "Business School", "School of Technology", "School of Science",
    "Institute of Innovation", "Technology Institute", "School of Engineering", "Institute of Leadership", "Business Institute",
    "Institute of Professional Studies", "Business and Technology Institute", "Science and Technology Institute",
    "Institute of Creative Arts", "School of Business Management", "Institute of Modern Technology", "Elite Science Institute",
    "Institute for Advanced Studies", "Institute of Leadership and Innovation", "Academy for Creative Arts"
]
nouns = [
    "Technology", "Science", "Engineering", "Business", "Art", "Medicine", "Management", "Education", "Innovation",
    "Excellence", "Research", "Leadership", "Professional Studies", "Information Technology", "Communication", "Design",
    "Information Sciences", "Biotechnology", "Environmental Sciences", "Creative Arts", "Humanities", "Social Sciences",
    "Health Sciences", "Music", "Performing Arts", "Hospitality", "Sports Management", "Economics", "Public Policy",
    "Computer Science", "Mathematics", "Astronomy", "Pharmacy", "Physics", "Chemistry", "Biology", "Geology",
    "Political Science", "Psychology", "History", "Philosophy", "Sociology", "Cultural Studies", "Agriculture",
    "Geography", "Statistics", "Nutrition", "Physical Education"
]
adjectives = [
    "Innovative", "Professional", "Excellence", "Modern", "Dynamic", "Creative", "Leading", "Prestigious", "Global",
    "International", "Cutting-edge", "Progressive", "Advanced", "Visionary", "Tech-savvy", "Contemporary", "Elite",
    "Top-tier", "Renowned", "Revolutionary", "Eminent", "Renowned", "Inclusive", "Interdisciplinary", "Intercontinental",
    "Inspirational", "Strategic", "Forward-thinking", "Transcendent", "Sustainable", "Multidisciplinary", "Digital",
    "Entrepreneurial", "Empowering", "Globalized", "Inclusive", "Ethical", "Futuristic", "Empowered", "Holistic", "Dynamic",
    "Resilient", "Open-minded", "Inclusive", "Eclectic", "Influential", "Respected", "Cutting-edge", "Inspirational"
]

data_types = [
    "Employee_ID",
    "Account_Number",
    "Transaction_ID",
    "Product_Code",
    "Customer_ID",
    "Order_Number",
    "License_Key",
    "Reference_Number",
    "Serial_Code",
    "Membership_ID",
    "Invoice_Number",
    "Tracking_Number",
    "Patient_ID",
    "Booking_Reference",
    "Student_ID",
    "Vehicle_ID",
    "Case_Number",
    "Reservation_Code",
    "Subscriber_Number",
    "Policy_Number"
]
sports_list = [
    "Football",
    "Basketball",
    "Soccer",
    "Cricket",
    "Tennis",
    "Golf",
    "Baseball",
    "Softball",
    "Volleyball",
    "Table Tennis",
    "Badminton",
    "Rugby",
    "Hockey",
    "Ice Hockey",
    "Boxing",
    "MMA (Mixed Martial Arts)",
    "Swimming",
    "Athletics",
    "Cycling",
    "Running",
    "Gymnastics",
    "Weightlifting",
    "Snowboarding",
    "Skiing",
    "Surfing",
    "Wrestling",
    "Karate",
    "Taekwondo",
    "Judo",
    "Archery",
    "Fencing",
    "Shooting",
    "Darts",
    "Chess",
    "Bowling",
    "Softball",
    "Handball",
    "Water Polo",
    "Squash",
    "Racquetball",
    "Polo",
    "Lacrosse",
    "Canoeing",
    "Kayaking",
    "Rowing",
    "Sailing",
    "Equestrian (Horseback Riding)"
]
hobbies_list = [
    "Reading",
    "Writing",
    "Drawing",
    "Painting",
    "Cooking",
    "Baking",
    "Photography",
    "Gardening",
    "Hiking",
    "Camping",
    "Fishing",
    "Birdwatching",
    "Traveling",
    "Yoga",
    "Meditation",
    "Running",
    "Cycling",
    "Dancing",
    "Singing",
    "Playing a Musical Instrument",
    "Listening to Music",
    "Watching Movies",
    "Gaming",
    "Collecting (e.g., stamps, coins, cards)",
    "Crafting (e.g., knitting, crochet)",
    "Woodworking",
    "DIY Projects",
    "Model Building",
    "Fossil Hunting",
    "Stargazing",
    "Surfing",
    "Scuba Diving",
    "Rock Climbing",
    "Skydiving",
    "Horseback Riding",
    "Skiing",
    "Snowboarding",
    "Motorcycling",
    "Car Restoration",
    "Sculpting",
    "Calligraphy",
    "Board Games",
    "Chess",
    "Puzzle Solving",
    "Volunteering",
    "Language Learning",
    "Cookbook Reading",
    "Food Tasting",
    "Wine Tasting"
]
